version: 2.1

jobs:
  build:
    docker:
      # This image has the latest cf-cli as well as zero downtime plugins, if needed.
      - image: circleci/node:12.13.0
    steps:
      - checkout
      - run: 
          name: Download WP
          command: |
            pwd && ls -l
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            # Set $DEV_CF_USERNAME and $DEV_CF_PASSWORD in CircleCI settings.
            # $DEV_CF_ORG, $DEV_CF_SPACE, and $APP_NAME can also be set in CircleCI settings or hardcoded here.
            cf api https://api.fr.cloud.gov
            cf auth "$DEV_CF_USERNAME" "$DEV_CF_PASSWORD"
            cf target -o "$DEV_CF_ORG" -s "$DEV_CF_SPACE"
            cf push onrr-cms-dev --no-start
      - run: 
          name: Setup wp configuration
          command: |
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            # Set $CF_USERNAME and $CF_PASSWORD in CircleCI settings.
            # $CF_ORG, $CF_SPACE, and $APP_NAME can also be set in CircleCI settings or hardcoded here.
            cf api https://api.fr.cloud.gov
            echo "$DEV_CF_USERNAME" "$DEV_CF_PASSWORD"
            cf auth "$DEV_CF_USERNAME" "$DEV_CF_PASSWORD"
            cf target -o "$DEV_CF_ORG" -s "$DEV_CF_SPACE"
            bash .circleci/setup.sh onrr-cms-dev
      - run:
          name: Install wordpress
          command: |
            pwd && ls -l
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            # Set $CF_USERNAME and $CF_PASSWORD in CircleCI settings.
            # $CF_ORG, $CF_SPACE, and $APP_NAME can also be set in CircleCI settings or hardcoded here.
            cf api https://api.fr.cloud.gov
            cf auth "$DEV_CF_USERNAME" "$DEV_CF_PASSWORD"
            cf target -o "$DEV_CF_ORG" -s "$DEV_CF_SPACE"
            cf push onrr-cms-dev -f ./manifest.yml
      - run: 
          name: Download and install WP-CLI
          command: |
            curl -O 'https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar'
      - run: 
          name: Make WP-CLI executable
          command: |
            chmod +x wp-cli.phar
            sudo mv wp-cli.phar /usr/local/bin/wp
      - run:
          name: Set site url
          command: ./wp-cli.phar option update blogname "$DEV_ADMIN_SITE_URL"
      - run: 
          name: Update admin username and password 
          command: ./wp-cli.phar user update admin --user_pass="$DEV_ADMIN_PASSWORD" --skip-packages
      - run:
          name: Update amdin email
          command: ./wp-cli.phar option update admin_email "$DEV_ADMIN_EMAIL"

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only: main
