version: 2.1

jobs:
  build:
    docker:
      # This image has the latest cf-cli as well as zero downtime plugins, if needed.
      - image: circleci/node:12.13.0
    steps:
      - checkout
      - run: 
          name: Download WP
          command: |
            pwd && ls -l
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            # Set $DEV_CF_USERNAME and $DEV_CF_PASSWORD in CircleCI settings.
            # $DEV_CF_ORG, $DEV_CF_SPACE, and $APP_NAME can also be set in CircleCI settings or hardcoded here.
            cf api https://api.fr.cloud.gov
            cf auth "$DEV_CF_USERNAME" "$DEV_CF_PASSWORD"
            cf target -o "$DEV_CF_ORG" -s "$DEV_CF_SPACE"
            cf push onrr-cms-dev --no-start
      - run: 
          name: Setup WP configuration
          command: |
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            # Set $CF_USERNAME and $CF_PASSWORD in CircleCI settings.
            # $CF_ORG, $CF_SPACE, and $APP_NAME can also be set in CircleCI settings or hardcoded here.
            cf api https://api.fr.cloud.gov
            echo "$DEV_CF_USERNAME" "$DEV_CF_PASSWORD"
            cf auth "$DEV_CF_USERNAME" "$DEV_CF_PASSWORD"
            cf target -o "$DEV_CF_ORG" -s "$DEV_CF_SPACE"
            bash .circleci/setup.sh onrr-cms-dev
      - run:
          name: Install WP
          command: |
            pwd && ls -l
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            # Set $CF_USERNAME and $CF_PASSWORD in CircleCI settings.
            # $CF_ORG, $CF_SPACE, and $APP_NAME can also be set in CircleCI settings or hardcoded here.
            cf api https://api.fr.cloud.gov
            cf auth "$DEV_CF_USERNAME" "$DEV_CF_PASSWORD"
            cf target -o "$DEV_CF_ORG" -s "$DEV_CF_SPACE"
            cf push onrr-cms-dev -f ./manifest.yml
      - run: 
          name: Flush permalinks
          command: |
            pwd && ls -l
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            # Set $CF_USERNAME and $CF_PASSWORD in CircleCI settings.
            # $CF_ORG, $CF_SPACE, and $APP_NAME can also be set in CircleCI settings or hardcoded here.
            cf api https://api.fr.cloud.gov
            cf auth "$DEV_CF_USERNAME" "$DEV_CF_PASSWORD"
            cf target -o "$DEV_CF_ORG" -s "$DEV_CF_SPACE"
            cf run-task onrr-cms-dev "php/bin/php htdocs/wp-cli.phar rewrite flush format '/%postname%/' --path='/home/vcap/app/htdocs'"
      - run: 
          name: Update admin user
          command: |
            pwd && ls -l
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            # Set $CF_USERNAME and $CF_PASSWORD in CircleCI settings.
            # $CF_ORG, $CF_SPACE, and $APP_NAME can also be set in CircleCI settings or hardcoded here.
            cf api https://api.fr.cloud.gov
            cf auth "$DEV_CF_USERNAME" "$DEV_CF_PASSWORD"
            cf target -o "$DEV_CF_ORG" -s "$DEV_CF_SPACE"
            cf run-task onrr-cms-dev "php/bin/php htdocs/wp-cli.phar user update admin --user_pass='$DEV_ADMIN_PASSWORD' --user_email='$DEV_ADMIN_EMAIL' --skip-packages --path='/home/vcap/app/htdocs'"
      - run:
          name: Update OS
          command: sudo apt-get update
      - run:
          name: Install mysql client
          command: sudo apt-get install --fix-missing mysql-client
      - run:
          name: Install cf service connect plugin
          command: |
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb 
            cf api https://api.fr.cloud.gov
            echo "$DEV_CF_USERNAME"
            cf auth "$DEV_CF_USERNAME" "$DEV_CF_PASSWORD"
            cf target -o "$DEV_CF_ORG" -s "$DEV_CF_SPACE"
            cf install-plugin -f https://github.com/cloud-gov/cf-service-connect/releases/download/1.1.0/cf-service-connect-linux-amd64
            cf connect-to-service -no-client onrr-cms-dev onrr-dev-mysql
      - run:
          name: Backup database
          command: mysqldump mysql://mysql:"$DEV_MYSQL_PASSWORD"@localhost:"$DEV_MYSQL_PORT"/mysql -f /tmp/database_backup.sql || echo $? 
      - store_artifacts:
          path: /tmp/database_backup.sql
          destination: database_backup.sql


workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only: main
