#!/bin/bash
APP_NAME=$1

cf set-env $APP_NAME AUTH_KEY $AUTH_KEY
cf set-env $APP_NAME SECURE_AUTH_KEY $SECURE_AUTH_KEY
cf set-env $APP_NAME LOGGED_IN_KEY $LOGGED_IN_KEY
cf set-env $APP_NAME NONCE_KEY $NONCE_KEY
cf set-env $APP_NAME AUTH_SALT $AUTH_SALT
cf set-env $APP_NAME SECURE_AUTH_SALT $SECURE_AUTH_SALT
cf set-env $APP_NAME LOGGED_IN_SALT $LOGGED_IN_SALT
cf set-env $APP_NAME NONCE_SALT $NONCE_SALT